//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorExplorer.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ControlLayout_Description {
            get {
                return ResourceManager.GetString("ControlLayout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string ControlLayout_Documentation {
            get {
                return ResourceManager.GetString("ControlLayout_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/docs/blazor/online-blazor/overview.html.
        /// </summary>
        public static string ControlLayout_DocumentationUrl {
            get {
                return ResourceManager.GetString("ControlLayout_DocumentationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string ControlLayout_Sample {
            get {
                return ResourceManager.GetString("ControlLayout_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ControlLayout_Settings {
            get {
                return ResourceManager.GetString("ControlLayout_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string ControlLayout_Source {
            get {
                return ResourceManager.GetString("ControlLayout_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string ControlsNav_Features {
            get {
                return ResourceManager.GetString("ControlsNav_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string CultureChinese {
            get {
                return ResourceManager.GetString("CultureChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string CultureDutch {
            get {
                return ResourceManager.GetString("CultureDutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string CultureEnglish {
            get {
                return ResourceManager.GetString("CultureEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string CultureFrench {
            get {
                return ResourceManager.GetString("CultureFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string CultureGerman {
            get {
                return ResourceManager.GetString("CultureGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string CultureItalian {
            get {
                return ResourceManager.GetString("CultureItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string CultureJapanese {
            get {
                return ResourceManager.GetString("CultureJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string CultureKorean {
            get {
                return ResourceManager.GetString("CultureKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string CultureSpanish {
            get {
                return ResourceManager.GetString("CultureSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/css/gcicons.css.
        /// </summary>
        public static string GcIconsCssPath {
            get {
                return ResourceManager.GetString("GcIconsCssPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentOne.
        /// </summary>
        public static string Layout_ComponentOne {
            get {
                return ResourceManager.GetString("Layout_ComponentOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/.
        /// </summary>
        public static string Layout_GrapeCityUrl {
            get {
                return ResourceManager.GetString("Layout_GrapeCityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESCIUS inc. All rights reserved..
        /// </summary>
        public static string Layout_License1 {
            get {
                return ResourceManager.GetString("Layout_License1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All product and company names here in may be trademarks of their respective owners..
        /// </summary>
        public static string Layout_License2 {
            get {
                return ResourceManager.GetString("Layout_License2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor Edition Control Explorer.
        /// </summary>
        public static string Layout_LongTitle {
            get {
                return ResourceManager.GetString("Layout_LongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/blazor.
        /// </summary>
        public static string Layout_ProductUrl {
            get {
                return ResourceManager.GetString("Layout_ProductUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor Control Explorer.
        /// </summary>
        public static string Layout_ShortTitle {
            get {
                return ResourceManager.GetString("Layout_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - C1 Blazor.
        /// </summary>
        public static string Layout_TitleSuffix {
            get {
                return ResourceManager.GetString("Layout_TitleSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you seen this? C1Studio Blazor Edition Controls.
        /// </summary>
        public static string Layout_TwitterText {
            get {
                return ResourceManager.GetString("Layout_TwitterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Controls.
        /// </summary>
        public static string NewControls {
            get {
                return ResourceManager.GetString("NewControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Controls.
        /// </summary>
        public static string PopularControls {
            get {
                return ResourceManager.GetString("PopularControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Applications.
        /// </summary>
        public static string Reference_Applications {
            get {
                return ResourceManager.GetString("Reference_Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SiteNav_About {
            get {
                return ResourceManager.GetString("SiteNav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/blazor.
        /// </summary>
        public static string SiteNav_AboutUrl {
            get {
                return ResourceManager.GetString("SiteNav_AboutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Theme &amp;gt;.
        /// </summary>
        public static string SiteNav_EditTheme {
            get {
                return ResourceManager.GetString("SiteNav_EditTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE TRIAL.
        /// </summary>
        public static string SiteNav_FreeTrial {
            get {
                return ResourceManager.GetString("SiteNav_FreeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/download/componentone-studio.
        /// </summary>
        public static string SiteNav_FreeTrialUrl {
            get {
                return ResourceManager.GetString("SiteNav_FreeTrialUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string SiteNav_Home {
            get {
                return ResourceManager.GetString("SiteNav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string SiteNav_Pricing {
            get {
                return ResourceManager.GetString("SiteNav_Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/pricing.
        /// </summary>
        public static string SiteNav_PricingUrl {
            get {
                return ResourceManager.GetString("SiteNav_PricingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string SiteNav_Support {
            get {
                return ResourceManager.GetString("SiteNav_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/support/contact.
        /// </summary>
        public static string SiteNav_SupportUrl {
            get {
                return ResourceManager.GetString("SiteNav_SupportUrl", resourceCulture);
            }
        }
    }
}
