//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SliderRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SliderRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorExplorer.Localization.SliderRes", typeof(SliderRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RangeSlider control allows you to visualize the process increase or decrease value by dragging the thumb in both lower and upper value. It can be horizontal or vertical, depending on the setting of the orientation property. This page also represents some other features of RangeSlider control..
        /// </summary>
        public static string SliderDescription {
            get {
                return ResourceManager.GetString("SliderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents a range slider component..
        /// </summary>
        public static string SliderSummary {
            get {
                return ResourceManager.GetString("SliderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal (here with the &lt;code&gt;RangeSliderScrollBehavior.Thumb&lt;/code&gt; scroll behavior).
        /// </summary>
        public static string SliderText00 {
            get {
                return ResourceManager.GetString("SliderText00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical (here with the &lt;code&gt;RangeSliderScrollBehavior.Range&lt;/code&gt; scroll behavior).
        /// </summary>
        public static string SliderText01 {
            get {
                return ResourceManager.GetString("SliderText01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are clickable areas at the ends of the track line. If user press and hold the pointer clicks logic will execute. For managing behavior set &lt;code&gt;ScrollBehavior&lt;/code&gt; parameter of the slider. Thus, the &lt;code&gt;RangeSliderScrollBehavior.Thumb&lt;/code&gt; logic will move a single thumb, which closer to the pointer. And &lt;code&gt;RangeSliderScrollBehavior.Range&lt;/code&gt; logic moves the whole range (both thumbs).&lt;br/&gt;
        ///        &lt;code&gt;Delay&lt;/code&gt; parameter defines the duration (in milliseconds) of holding before first  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SliderText02 {
            get {
                return ResourceManager.GetString("SliderText02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        public static string SliderText03 {
            get {
                return ResourceManager.GetString("SliderText03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEnabled.
        /// </summary>
        public static string SliderText04 {
            get {
                return ResourceManager.GetString("SliderText04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customization.
        /// </summary>
        public static string SliderText05 {
            get {
                return ResourceManager.GetString("SliderText05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Navigation.
        /// </summary>
        public static string SliderText06 {
            get {
                return ResourceManager.GetString("SliderText06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;code&gt;TabIndex&lt;/code&gt; (0 by default) allows to set tabindex to define the order of the focus between the elements..
        /// </summary>
        public static string SliderText07 {
            get {
                return ResourceManager.GetString("SliderText07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string SliderText08 {
            get {
                return ResourceManager.GetString("SliderText08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arrows increases the &lt;code&gt;LowerValue&lt;/code&gt;/&lt;code&gt;UpperValue&lt;/code&gt; of the C1RangeSlider with the &lt;code&gt;SmallValueChange&lt;/code&gt;.
        /// </summary>
        public static string SliderText09 {
            get {
                return ResourceManager.GetString("SliderText09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arrows decreases the &lt;code&gt;LowerValue&lt;/code&gt;/&lt;code&gt;UpperValue&lt;/code&gt; of the C1RangeSlider with the &lt;code&gt;SmallValueChange&lt;/code&gt;.
        /// </summary>
        public static string SliderText10 {
            get {
                return ResourceManager.GetString("SliderText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string SliderTitle {
            get {
                return ResourceManager.GetString("SliderTitle", resourceCulture);
            }
        }
    }
}
