//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CalendarRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CalendarRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorExplorer.Localization.CalendarRes", typeof(CalendarRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1Calendar supports customising the style and appearance of the C1Calendar including slot border and color..
        /// </summary>
        public static string CustomStylesDescription {
            get {
                return ResourceManager.GetString("CustomStylesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Styles.
        /// </summary>
        public static string CustomStylesTitle {
            get {
                return ResourceManager.GetString("CustomStylesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Date.
        /// </summary>
        public static string DisplayDateText {
            get {
                return ResourceManager.GetString("DisplayDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1Calendar supports customising the button icon by a html struct..
        /// </summary>
        public static string IconTemplateDescription {
            get {
                return ResourceManager.GetString("IconTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Template.
        /// </summary>
        public static string IconTemplateTitle {
            get {
                return ResourceManager.GetString("IconTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        public static string Incident {
            get {
                return ResourceManager.GetString("Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Found.
        /// </summary>
        public static string IssueFound {
            get {
                return ResourceManager.GetString("IssueFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1Calendar supports customising of the slot item by a html struct..
        /// </summary>
        public static string ItemTemplateDescription {
            get {
                return ResourceManager.GetString("ItemTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Template.
        /// </summary>
        public static string ItemTemplateTitle {
            get {
                return ResourceManager.GetString("ItemTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section briefly explains how to bind the value to the C1Calendar component..
        /// </summary>
        public static string ModelBindingDescription {
            get {
                return ResourceManager.GetString("ModelBindingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Binding.
        /// </summary>
        public static string ModelBindingTitle {
            get {
                return ResourceManager.GetString("ModelBindingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Months.
        /// </summary>
        public static string MultipleMonthsTitle {
            get {
                return ResourceManager.GetString("MultipleMonthsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar displays months following MonthCount Property entered by user code..
        /// </summary>
        public static string MultipleMonthsTitleDescription {
            get {
                return ResourceManager.GetString("MultipleMonthsTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The example shows a C1Calendar control that allows users to select the date with a single click..
        /// </summary>
        public static string OverviewDescription {
            get {
                return ResourceManager.GetString("OverviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The C1Calendar control displays a one-month calendar and allows users to select a date..
        /// </summary>
        public static string OverviewSummary {
            get {
                return ResourceManager.GetString("OverviewSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string OverviewTitle {
            get {
                return ResourceManager.GetString("OverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Date.
        /// </summary>
        public static string SelectedDateText {
            get {
                return ResourceManager.GetString("SelectedDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1Calendar control can prevent users from selecting values outside of a range determined by the min and max properties..
        /// </summary>
        public static string UsingRangesDescription {
            get {
                return ResourceManager.GetString("UsingRangesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Ranges.
        /// </summary>
        public static string UsingRangesTitle {
            get {
                return ResourceManager.GetString("UsingRangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows how to set item-validator attribute to a function to determine whether dates are valid for selection..
        /// </summary>
        public static string ValidationDescription {
            get {
                return ResourceManager.GetString("ValidationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this Calendar control to select a date. Notice you won&apos;t be able to select weekends..
        /// </summary>
        public static string ValidationHeader {
            get {
                return ResourceManager.GetString("ValidationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string ValidationTitle {
            get {
                return ResourceManager.GetString("ValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
