//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NumericBoxRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumericBoxRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorExplorer.Localization.NumericBoxRes", typeof(NumericBoxRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding value.
        /// </summary>
        public static string Binding {
            get {
                return ResourceManager.GetString("Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle ValueChanged event.
        /// </summary>
        public static string BindingAndHandleEvent {
            get {
                return ResourceManager.GetString("BindingAndHandleEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomStyle &amp; Layout.
        /// </summary>
        public static string CustomStyleAndLayout {
            get {
                return ResourceManager.GetString("CustomStyleAndLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish editing by pressing on Enter.
        /// </summary>
        public static string FinishEditingByPressingEnter {
            get {
                return ResourceManager.GetString("FinishEditingByPressingEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEnabled.
        /// </summary>
        public static string IsEnabled {
            get {
                return ResourceManager.GetString("IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsReadOnly.
        /// </summary>
        public static string IsReadOnly {
            get {
                return ResourceManager.GetString("IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section briefly explains how to bind the value to the C1NumericBox component..
        /// </summary>
        public static string ModelBindingDescription {
            get {
                return ResourceManager.GetString("ModelBindingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Binding.
        /// </summary>
        public static string ModelBindingTitle {
            get {
                return ResourceManager.GetString("ModelBindingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The example creates several C1NumericBox controls and shows the effect of using different formats..
        /// </summary>
        public static string OverviewDescription {
            get {
                return ResourceManager.GetString("OverviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The C1NumericBox control allows users to enter numbers..
        /// </summary>
        public static string OverviewSummary {
            get {
                return ResourceManager.GetString("OverviewSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string OverviewTitle {
            get {
                return ResourceManager.GetString("OverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place buttons on the right.
        /// </summary>
        public static string PlaceButtonsOnTheRight {
            get {
                return ResourceManager.GetString("PlaceButtonsOnTheRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place buttons side by side.
        /// </summary>
        public static string PlaceButtonsSideBySide {
            get {
                return ResourceManager.GetString("PlaceButtonsSideBySide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        public static string Placeholder {
            get {
                return ResourceManager.GetString("Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step - Max &amp; Min.
        /// </summary>
        public static string StepAndMaxMin {
            get {
                return ResourceManager.GetString("StepAndMaxMin", resourceCulture);
            }
        }
    }
}
