//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewerRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewerRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorExplorer.Localization.ViewerRes", typeof(ViewerRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component opens the FlexReport document and shows in the FlexViewer. Use the FlexReport.Load method with the FlexReport document&apos;s path to open it in the FlexViewer instance..
        /// </summary>
        public static string FlexReportViewerDescription {
            get {
                return ResourceManager.GetString("FlexReportViewerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates how to use the FlexViewer to view the FlexReport documents..
        /// </summary>
        public static string FlexReportViewerSummary {
            get {
                return ResourceManager.GetString("FlexReportViewerSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexReport viewer.
        /// </summary>
        public static string FlexReportViewerTitle {
            get {
                return ResourceManager.GetString("FlexReportViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component opens PDF document and shows in the FlexViewer. Use the C1PdfDocumentSource.LoadFromFile method with PDF document&apos;s path to open it in the FlexViewer instance..
        /// </summary>
        public static string PdfViewerDescription {
            get {
                return ResourceManager.GetString("PdfViewerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates how to use the FlexViewer to view Adobe PDF document..
        /// </summary>
        public static string PdfViewerSummary {
            get {
                return ResourceManager.GetString("PdfViewerSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe PDF viewer.
        /// </summary>
        public static string PdfViewerTitle {
            get {
                return ResourceManager.GetString("PdfViewerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component opens the SSRS document and shows in the FlexViewer. Use the C1SSRSDocumentSource.DocumentLocation property with the SSRS server URL to open the report in the FlexViewer instance..
        /// </summary>
        public static string SsrsViewerDescription {
            get {
                return ResourceManager.GetString("SsrsViewerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrates how to use the FlexViewer to view the SSRS document source..
        /// </summary>
        public static string SsrsViewerSummary {
            get {
                return ResourceManager.GetString("SsrsViewerSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSRS viewer.
        /// </summary>
        public static string SsrsViewerTitle {
            get {
                return ResourceManager.GetString("SsrsViewerTitle", resourceCulture);
            }
        }
    }
}
