//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestmentCalculator.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InvestmentCalculator.Client.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure total number of periods is upto 360 !!!.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Rate of Return:.
        /// </summary>
        public static string AnnualRate {
            get {
                return ResourceManager.GetString("AnnualRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate your investment returns..
        /// </summary>
        public static string CalculateInvReturns {
            get {
                return ResourceManager.GetString("CalculateInvReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Amount per Period:.
        /// </summary>
        public static string DepositAmountPerPeriod {
            get {
                return ResourceManager.GetString("DepositAmountPerPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of Investment (In Years):.
        /// </summary>
        public static string DurationOfInvestment {
            get {
                return ResourceManager.GetString("DurationOfInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Balance(FV):.
        /// </summary>
        public static string EndingBalance {
            get {
                return ResourceManager.GetString("EndingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter values into the yellow boxes..
        /// </summary>
        public static string EnterValues {
            get {
                return ResourceManager.GetString("EnterValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Balance.
        /// </summary>
        public static string InitialBalance {
            get {
                return ResourceManager.GetString("InitialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Investment Amount:.
        /// </summary>
        public static string InitialInvAmount {
            get {
                return ResourceManager.GetString("InitialInvAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Earned.
        /// </summary>
        public static string InterestEarned {
            get {
                return ResourceManager.GetString("InterestEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Calculator.
        /// </summary>
        public static string InvestmentCalculator {
            get {
                return ResourceManager.GetString("InvestmentCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Balance.
        /// </summary>
        public static string NewBalance {
            get {
                return ResourceManager.GetString("NewBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deposit.
        /// </summary>
        public static string NewDeposit {
            get {
                return ResourceManager.GetString("NewDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Deposits Per Year:.
        /// </summary>
        public static string NumberDepositsPerYear {
            get {
                return ResourceManager.GetString("NumberDepositsPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results will be shown in the green boxes..
        /// </summary>
        public static string ResultsShownGreenBoxes {
            get {
                return ResourceManager.GetString("ResultsShownGreenBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Interest Income:.
        /// </summary>
        public static string TotalIncome {
            get {
                return ResourceManager.GetString("TotalIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Periods (Upto 360):.
        /// </summary>
        public static string TotalNumOfPeriods {
            get {
                return ResourceManager.GetString("TotalNumOfPeriods", resourceCulture);
            }
        }
    }
}
