//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreeViewExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreeViewExplorer.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accordion Tree.
        /// </summary>
        public static string Accordion_Tree {
            get {
                return ResourceManager.GetString("Accordion_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding.
        /// </summary>
        public static string Adding {
            get {
                return ResourceManager.GetString("Adding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Node for Bound TreeView.
        /// </summary>
        public static string Adding_BoundTree {
            get {
                return ResourceManager.GetString("Adding_BoundTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First child.
        /// </summary>
        public static string Adding_FirstChild {
            get {
                return ResourceManager.GetString("Adding_FirstChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last child.
        /// </summary>
        public static string Adding_LastChild {
            get {
                return ResourceManager.GetString("Adding_LastChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Node for UnBound TreeView.
        /// </summary>
        public static string Adding_UnBoundTree {
            get {
                return ResourceManager.GetString("Adding_UnBoundTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Adding new item for C1TreeView, &lt;b&gt;ItemsSource must implement INotifyCollectionChanged&lt;/b&gt; to allow the control to get notified of the changes, then it will be reflected automatically in the control. &lt;br/&gt; In this sample, we use &lt;i&gt;ObservableCollection&amp;lt;T&amp;gt;&lt;/i&gt; which is a built-in implementation of a data collection that implements the INotifyCollectionChanged interface..
        /// </summary>
        public static string AddItemDescription {
            get {
                return ResourceManager.GetString("AddItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Accordion.
        /// </summary>
        public static string Clean_Accordion {
            get {
                return ResourceManager.GetString("Clean_Accordion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigating to &lt;b&gt;** {0} **&lt;/b&gt;.
        /// </summary>
        public static string NavigationTo {
            get {
                return ResourceManager.GetString("NavigationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Borders.
        /// </summary>
        public static string Node_Borders {
            get {
                return ResourceManager.GetString("Node Borders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes.
        /// </summary>
        public static string Nodes {
            get {
                return ResourceManager.GetString("Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        public static string Removing {
            get {
                return ResourceManager.GetString("Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected item.
        /// </summary>
        public static string RemovingBtn {
            get {
                return ResourceManager.GetString("RemovingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Left.
        /// </summary>
        public static string RightToLeft {
            get {
                return ResourceManager.GetString("RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styling.
        /// </summary>
        public static string Styling {
            get {
                return ResourceManager.GetString("Styling", resourceCulture);
            }
        }
    }
}
