//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AutoCompleteRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoCompleteRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorExplorer.Localization.AutoCompleteRes", typeof(AutoCompleteRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the auto complete drop-down with item templates. This demo shows how to display images and text within each item of the C1AutoComplete..
        /// </summary>
        public static string CustomItemDescription {
            get {
                return ResourceManager.GetString("CustomItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the auto complete drop-down with item templates..
        /// </summary>
        public static string CustomItemSummary {
            get {
                return ResourceManager.GetString("CustomItemSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Item.
        /// </summary>
        public static string CustomItemTitle {
            get {
                return ResourceManager.GetString("CustomItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows how to change the list source dynamically as the user types. It uses a modified feed to search for videos on YouTube..
        /// </summary>
        public static string DynamicSourceDescription {
            get {
                return ResourceManager.GetString("DynamicSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows how to change the list source dynamically as the user types..
        /// </summary>
        public static string DynamicSourceSummary {
            get {
                return ResourceManager.GetString("DynamicSourceSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic source.
        /// </summary>
        public static string DynamicSourceTitle {
            get {
                return ResourceManager.GetString("DynamicSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The C1AutoComplete control for Blazor provides text input and selection from a drop-down with auto-complete suggestions. It also supports item template customization and auto-complete text highlighting..
        /// </summary>
        public static string OverviewDescription {
            get {
                return ResourceManager.GetString("OverviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OverviewSummary {
            get {
                return ResourceManager.GetString("OverviewSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string OverviewTitle {
            get {
                return ResourceManager.GetString("OverviewTitle", resourceCulture);
            }
        }
    }
}
