
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
		<PackageReference Include="System.Text.Json" Version="9.0.0" />
		<PackageReference Include="C1.DataCollection" Version="10.0.20261.8" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include=".sa3licx" />
	</ItemGroup>
</Project>
