//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FlexChartRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlexChartRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorExplorer.Localization.FlexChartRes", typeof(FlexChartRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexChart supports animation when loading or updating data..
        /// </summary>
        public static string AnimationDescription {
            get {
                return ResourceManager.GetString("AnimationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexChart Animation.
        /// </summary>
        public static string AnimationSummary {
            get {
                return ResourceManager.GetString("AnimationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string AnimationTitle {
            get {
                return ResourceManager.GetString("AnimationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlexChart control supports various built-in annotations such as Rectangle, Square, Circle, Ellipse, Line, Polygon, Image, and Text. In this demo the annotations are used to display plot quadrants as well as country flags..
        /// </summary>
        public static string AnnotationsDescription {
            get {
                return ResourceManager.GetString("AnnotationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows FlexChart with rich annotations.
        /// </summary>
        public static string AnnotationsSummary {
            get {
                return ResourceManager.GetString("AnnotationsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        public static string AnnotationsTitle {
            get {
                return ResourceManager.GetString("AnnotationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis scrollbar allows to select scale and scroll through the data range..
        /// </summary>
        public static string AxisScrollbarDescription {
            get {
                return ResourceManager.GetString("AxisScrollbarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Scrollbar.
        /// </summary>
        public static string AxisScrollbarSummary {
            get {
                return ResourceManager.GetString("AxisScrollbarSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis Scrollbar.
        /// </summary>
        public static string AxisScrollbarTitle {
            get {
                return ResourceManager.GetString("AxisScrollbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows a basic line chart with multiple series..
        /// </summary>
        public static string BasicLineDescription {
            get {
                return ResourceManager.GetString("BasicLineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Line Chart.
        /// </summary>
        public static string BasicLineSummary {
            get {
                return ResourceManager.GetString("BasicLineSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Line Chart.
        /// </summary>
        public static string BasicLineTitle {
            get {
                return ResourceManager.GetString("BasicLineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box and Whisker series (AKA boxplots) show groups of numerical data through their quartiles. They have lines extending vertically from the boxes (whiskers) indicating variability outside the upper and lower quartiles..
        /// </summary>
        public static string BoxWhiskerDescription {
            get {
                return ResourceManager.GetString("BoxWhiskerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Inner Points.
        /// </summary>
        public static string BoxWhiskerInnerPoints {
            get {
                return ResourceManager.GetString("BoxWhiskerInnerPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Mean Line.
        /// </summary>
        public static string BoxWhiskerMeanLine {
            get {
                return ResourceManager.GetString("BoxWhiskerMeanLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Mean Marks.
        /// </summary>
        public static string BoxWhiskerMeanMarks {
            get {
                return ResourceManager.GetString("BoxWhiskerMeanMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Outliers.
        /// </summary>
        public static string BoxWhiskerOutliers {
            get {
                return ResourceManager.GetString("BoxWhiskerOutliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Box &amp; Whisker Chart.
        /// </summary>
        public static string BoxWhiskerSummary {
            get {
                return ResourceManager.GetString("BoxWhiskerSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box &amp; Whisker Chart.
        /// </summary>
        public static string BoxWhiskerTitle {
            get {
                return ResourceManager.GetString("BoxWhiskerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break-Even chart is a chart that shows the sales volume level at which total costs equal sales..
        /// </summary>
        public static string BreakEvenDescription {
            get {
                return ResourceManager.GetString("BreakEvenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Even Plot.
        /// </summary>
        public static string BreakEvenSummary {
            get {
                return ResourceManager.GetString("BreakEvenSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Even Plot.
        /// </summary>
        public static string BreakEvenTitle {
            get {
                return ResourceManager.GetString("BreakEvenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows a bubble chart with multiple series..
        /// </summary>
        public static string BubbleDescription {
            get {
                return ResourceManager.GetString("BubbleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble Plot.
        /// </summary>
        public static string BubbleSummary {
            get {
                return ResourceManager.GetString("BubbleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble Plot.
        /// </summary>
        public static string BubbleTitle {
            get {
                return ResourceManager.GetString("BubbleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows a combination of Column and LineSymbols chart types. The chart has two series: the first one is Column (inherited from parent chart) and the second series is LineSymbols..
        /// </summary>
        public static string ColumnLineDescription {
            get {
                return ResourceManager.GetString("ColumnLineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column and LineSymbols Combination.
        /// </summary>
        public static string ColumnLineSummary {
            get {
                return ResourceManager.GetString("ColumnLineSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination.
        /// </summary>
        public static string ColumnLineTitle {
            get {
                return ResourceManager.GetString("ColumnLineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows a column chart with data labels..
        /// </summary>
        public static string ColumnWithDataLabelsDescription {
            get {
                return ResourceManager.GetString("ColumnWithDataLabelsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chart With Data Labels.
        /// </summary>
        public static string ColumnWithDataLabelsSummary {
            get {
                return ResourceManager.GetString("ColumnWithDataLabelsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column With Data Labels.
        /// </summary>
        public static string ColumnWithDataLabelsTitle {
            get {
                return ResourceManager.GetString("ColumnWithDataLabelsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows a column chart with negative values to show drawing below the X axis..
        /// </summary>
        public static string ColumnWithNegativeValuesDescription {
            get {
                return ResourceManager.GetString("ColumnWithNegativeValuesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chart With Negative Values.
        /// </summary>
        public static string ColumnWithNegativeValuesSummary {
            get {
                return ResourceManager.GetString("ColumnWithNegativeValuesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column With Negative Values.
        /// </summary>
        public static string ColumnWithNegativeValuesTitle {
            get {
                return ResourceManager.GetString("ColumnWithNegativeValuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ErrorBar class extends the regular Series class to provide error bars that can be added on top of the regular series data..
        /// </summary>
        public static string ErrorBarDescription {
            get {
                return ResourceManager.GetString("ErrorBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Amount:.
        /// </summary>
        public static string ErrorBarErrorAmount {
            get {
                return ResourceManager.GetString("ErrorBarErrorAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show ErrorBar chart.
        /// </summary>
        public static string ErrorBarSummary {
            get {
                return ResourceManager.GetString("ErrorBarSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorBar Chart.
        /// </summary>
        public static string ErrorBarTitle {
            get {
                return ResourceManager.GetString("ErrorBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funnel charts show values along multiple stages in a process.
        ///
        ///For example, you could use a funnel chart to show the number of sales prospects at each stage in a sales pipeline. Typically, the values decrease gradually, making the bars resemble a funnel..
        /// </summary>
        public static string FunnelDescription {
            get {
                return ResourceManager.GetString("FunnelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck Height:.
        /// </summary>
        public static string FunnelNeckHeight {
            get {
                return ResourceManager.GetString("FunnelNeckHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck Width:.
        /// </summary>
        public static string FunnelNeckWidth {
            get {
                return ResourceManager.GetString("FunnelNeckWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funnel Chart.
        /// </summary>
        public static string FunnelSummary {
            get {
                return ResourceManager.GetString("FunnelSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funnel Chart.
        /// </summary>
        public static string FunnelTitle {
            get {
                return ResourceManager.GetString("FunnelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funnel Type:.
        /// </summary>
        public static string FunnelType {
            get {
                return ResourceManager.GetString("FunnelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance:.
        /// </summary>
        public static string HistogramAppearance {
            get {
                return ResourceManager.GetString("HistogramAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin Size:.
        /// </summary>
        public static string HistogramBinSize {
            get {
                return ResourceManager.GetString("HistogramBinSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Mode.
        /// </summary>
        public static string HistogramCumulativeMode {
            get {
                return ResourceManager.GetString("HistogramCumulativeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Histogram chart is used to study the distribution of non-categorical data by dividing it into bins of specified width. It plots the frequency of data items that fall in each of these bins..
        /// </summary>
        public static string HistogramDescription {
            get {
                return ResourceManager.GetString("HistogramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Curve.
        /// </summary>
        public static string HistogramNormalCurve {
            get {
                return ResourceManager.GetString("HistogramNormalCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows Histogram Chart.
        /// </summary>
        public static string HistogramSummary {
            get {
                return ResourceManager.GetString("HistogramSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram Chart.
        /// </summary>
        public static string HistogramTitle {
            get {
                return ResourceManager.GetString("HistogramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart type:.
        /// </summary>
        public static string IndexChartType {
            get {
                return ResourceManager.GetString("IndexChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It binds the chart to a data source and allows you to select the chart type, series stacking, palette and rotation..
        /// </summary>
        public static string IndexDescription {
            get {
                return ResourceManager.GetString("IndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette:.
        /// </summary>
        public static string IndexPalette {
            get {
                return ResourceManager.GetString("IndexPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacking:.
        /// </summary>
        public static string IndexStacking {
            get {
                return ResourceManager.GetString("IndexStacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows basic FlexChart features..
        /// </summary>
        public static string IndexSummary {
            get {
                return ResourceManager.GetString("IndexSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexChart Overview..
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows several advanced legend features, like scrolling and grouping..
        /// </summary>
        public static string LegendDescription {
            get {
                return ResourceManager.GetString("LegendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Legend Features.
        /// </summary>
        public static string LegendSummary {
            get {
                return ResourceManager.GetString("LegendSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string LegendTitle {
            get {
                return ResourceManager.GetString("LegendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample shows a line chart with missing points (interpolate nulls)..
        /// </summary>
        public static string LineWithGapsDescription {
            get {
                return ResourceManager.GetString("LineWithGapsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolate Nulls.
        /// </summary>
        public static string LineWithGapsInterpolateNulls {
            get {
                return ResourceManager.GetString("LineWithGapsInterpolateNulls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Chart With Gaps.
        /// </summary>
        public static string LineWithGapsSummary {
            get {
                return ResourceManager.GetString("LineWithGapsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line With Gaps.
        /// </summary>
        public static string LineWithGapsTitle {
            get {
                return ResourceManager.GetString("LineWithGapsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LineMarker class allows you to add a mouse-driven cursor to your charts. The cursor consists of a text element used to display information about the point under the mouse and optional lines to indicate the exact position of the mouse..
        /// </summary>
        public static string MarkerDescription {
            get {
                return ResourceManager.GetString("MarkerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        public static string MarkerInteraction {
            get {
                return ResourceManager.GetString("MarkerInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows plot with line marker.
        /// </summary>
        public static string MarkerSummary {
            get {
                return ResourceManager.GetString("MarkerSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Marker.
        /// </summary>
        public static string MarkerTitle {
            get {
                return ResourceManager.GetString("MarkerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample shows how to create multiple pie charts based on the same data source.
        ///
        ///To create multiple pie charts, just specify several comma-separated properties in FlexPie.binding..
        /// </summary>
        public static string MultiplePiesDescription {
            get {
                return ResourceManager.GetString("MultiplePiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Pie Charts.
        /// </summary>
        public static string MultiplePiesSummary {
            get {
                return ResourceManager.GetString("MultiplePiesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Pie Charts.
        /// </summary>
        public static string MultiplePiesTitle {
            get {
                return ResourceManager.GetString("MultiplePiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Data.
        /// </summary>
        public static string NewData {
            get {
                return ResourceManager.GetString("NewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexPie supports animation when loading or updating data. Use FlexPie.AnimationSettings property to enable animation..
        /// </summary>
        public static string PieAnimationDescription {
            get {
                return ResourceManager.GetString("PieAnimationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexPie Animation.
        /// </summary>
        public static string PieAnimationSummary {
            get {
                return ResourceManager.GetString("PieAnimationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie Animation.
        /// </summary>
        public static string PieAnimationTitle {
            get {
                return ResourceManager.GetString("PieAnimationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It binds the chart to a data source and allows you to select palette and change various options..
        /// </summary>
        public static string PieIndexDescription {
            get {
                return ResourceManager.GetString("PieIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerRadius:.
        /// </summary>
        public static string PieIndexInnerRadius {
            get {
                return ResourceManager.GetString("PieIndexInnerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset:.
        /// </summary>
        public static string PieIndexOffset {
            get {
                return ResourceManager.GetString("PieIndexOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette:.
        /// </summary>
        public static string PieIndexPalette {
            get {
                return ResourceManager.GetString("PieIndexPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows basic FlexPie features..
        /// </summary>
        public static string PieIndexSummary {
            get {
                return ResourceManager.GetString("PieIndexSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie chart overview..
        /// </summary>
        public static string PieIndexTitle {
            get {
                return ResourceManager.GetString("PieIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample below shows FlexPie&apos;s selection feature. To enable selection in FlexPie, set the &apos;SelectionMode&apos; property to &apos;Point&apos;..
        /// </summary>
        public static string PieSelectionDescription {
            get {
                return ResourceManager.GetString("PieSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Item Offset:.
        /// </summary>
        public static string PieSelectionOffset {
            get {
                return ResourceManager.GetString("PieSelectionOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Item Position:.
        /// </summary>
        public static string PieSelectionPosition {
            get {
                return ResourceManager.GetString("PieSelectionPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection in FlexPie.
        /// </summary>
        public static string PieSelectionSummary {
            get {
                return ResourceManager.GetString("PieSelectionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexPie Selection.
        /// </summary>
        public static string PieSelectionTitle {
            get {
                return ResourceManager.GetString("PieSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demos shows FlexChart with three plot areas..
        /// </summary>
        public static string PlotAreasDescription {
            get {
                return ResourceManager.GetString("PlotAreasDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows chart with multiple plot areas.
        /// </summary>
        public static string PlotAreasSummary {
            get {
                return ResourceManager.GetString("PlotAreasSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Plot Areas.
        /// </summary>
        public static string PlotAreasTitle {
            get {
                return ResourceManager.GetString("PlotAreasTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows a FlexRadar control with multiple series..
        /// </summary>
        public static string RadarDescription {
            get {
                return ResourceManager.GetString("RadarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Basic FlexRadar features.
        /// </summary>
        public static string RadarSummary {
            get {
                return ResourceManager.GetString("RadarSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar Chart.
        /// </summary>
        public static string RadarTitle {
            get {
                return ResourceManager.GetString("RadarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows a range column scenario similar to a Gantt chart..
        /// </summary>
        public static string RangeColumnDescription {
            get {
                return ResourceManager.GetString("RangeColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Column Chart.
        /// </summary>
        public static string RangeColumnSummary {
            get {
                return ResourceManager.GetString("RangeColumnSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Column.
        /// </summary>
        public static string RangeColumnTitle {
            get {
                return ResourceManager.GetString("RangeColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin Mode:.
        /// </summary>
        public static string RangedHistogramBinMode {
            get {
                return ResourceManager.GetString("RangedHistogramBinMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin Width:.
        /// </summary>
        public static string RangedHistogramBinWidth {
            get {
                return ResourceManager.GetString("RangedHistogramBinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Category.
        /// </summary>
        public static string RangedHistogramByCategory {
            get {
                return ResourceManager.GetString("RangedHistogramByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unique Histogram chart that can be used to study categorical as well as non-categorical data. Provides multiple binning options as well as support for Overflow and Underflow bins..
        /// </summary>
        public static string RangedHistogramDescription {
            get {
                return ResourceManager.GetString("RangedHistogramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Bins:.
        /// </summary>
        public static string RangedHistogramNumBins {
            get {
                return ResourceManager.GetString("RangedHistogramNumBins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows Ranged Histogram Chart.
        /// </summary>
        public static string RangedHistogramSummary {
            get {
                return ResourceManager.GetString("RangedHistogramSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged Histogram Chart.
        /// </summary>
        public static string RangedHistogramTitle {
            get {
                return ResourceManager.GetString("RangedHistogramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RangeSelector allows to choose displayed range on another chart..
        /// </summary>
        public static string RangeSelectorDescription {
            get {
                return ResourceManager.GetString("RangeSelectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexChart Range Selector.
        /// </summary>
        public static string RangeSelectorSummary {
            get {
                return ResourceManager.GetString("RangeSelectorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Selector.
        /// </summary>
        public static string RangeSelectorTitle {
            get {
                return ResourceManager.GetString("RangeSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample demonstrates FlexChart&apos;s selection feature. FlexChart provides two different selection modes: in Point mode, clicking a data point would show it as selected with the current SelectionStyle. In Series mode, clicking a data point would show all the data points in that series as selected with the current SelectionStyle..
        /// </summary>
        public static string SelectionDescription {
            get {
                return ResourceManager.GetString("SelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Mode:.
        /// </summary>
        public static string SelectionMode {
            get {
                return ResourceManager.GetString("SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection in FlexChart.
        /// </summary>
        public static string SelectionSummary {
            get {
                return ResourceManager.GetString("SelectionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string SelectionTitle {
            get {
                return ResourceManager.GetString("SelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample shows stacked area 100% chart..
        /// </summary>
        public static string Stacked100pcAreaDescription {
            get {
                return ResourceManager.GetString("Stacked100pcAreaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked 100% Area Chart.
        /// </summary>
        public static string Stacked100pcAreaSummary {
            get {
                return ResourceManager.GetString("Stacked100pcAreaSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked 100% Area.
        /// </summary>
        public static string Stacked100pcAreaTitle {
            get {
                return ResourceManager.GetString("Stacked100pcAreaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows stacking applied to a bar chart, which is similar to a rotated column chart.
        ///
        ///By default, items on the Y axis start from the bottom of the chart, so the first items appear at the bottom and the last at the top.
        ///
        ///If you reverse the Y axis, items will start at the top of the, which is often a more natural order..
        /// </summary>
        public static string StackedBarDescription {
            get {
                return ResourceManager.GetString("StackedBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Bar.
        /// </summary>
        public static string StackedBarSummary {
            get {
                return ResourceManager.GetString("StackedBarSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacked Bar.
        /// </summary>
        public static string StackedBarTitle {
            get {
                return ResourceManager.GetString("StackedBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows line and area step charts..
        /// </summary>
        public static string StepChartDescription {
            get {
                return ResourceManager.GetString("StepChartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Charts.
        /// </summary>
        public static string StepChartSummary {
            get {
                return ResourceManager.GetString("StepChartSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Charts.
        /// </summary>
        public static string StepChartTitle {
            get {
                return ResourceManager.GetString("StepChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows Sunburst chart that visualizes hierarchical data..
        /// </summary>
        public static string SunburstDescription {
            get {
                return ResourceManager.GetString("SunburstDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows Sunburst chart.
        /// </summary>
        public static string SunburstSummary {
            get {
                return ResourceManager.GetString("SunburstSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunburst chart.
        /// </summary>
        public static string SunburstTitle {
            get {
                return ResourceManager.GetString("SunburstTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows TreeMap chart with hierarchical data..
        /// </summary>
        public static string TreeMapDescription {
            get {
                return ResourceManager.GetString("TreeMapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows TreeMap chart.
        /// </summary>
        public static string TreeMapSummary {
            get {
                return ResourceManager.GetString("TreeMapSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeMap overview.
        /// </summary>
        public static string TreeMapTitle {
            get {
                return ResourceManager.GetString("TreeMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TrendLine class extends the regular Series class to provide a calculated series based on the data and parameters you select..
        /// </summary>
        public static string TrendLineDescription {
            get {
                return ResourceManager.GetString("TrendLineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Type:.
        /// </summary>
        public static string TrendLineFitType {
            get {
                return ResourceManager.GetString("TrendLineFitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order:.
        /// </summary>
        public static string TrendLineOrder {
            get {
                return ResourceManager.GetString("TrendLineOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows plot with trend Line.
        /// </summary>
        public static string TrendLineSummary {
            get {
                return ResourceManager.GetString("TrendLineSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend Line.
        /// </summary>
        public static string TrendLineTitle {
            get {
                return ResourceManager.GetString("TrendLineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Data.
        /// </summary>
        public static string UpdateData {
            get {
                return ResourceManager.GetString("UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterfall charts help in understanding the cumulative effect of sequentially introduced positive or negative values. The Waterfall chart is also known as a &quot;flying bricks&quot; chart or Mario chart due to the apparent suspension of columns in mid-air..
        /// </summary>
        public static string WaterfallDescription {
            get {
                return ResourceManager.GetString("WaterfallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Lines.
        /// </summary>
        public static string WaterfallLines {
            get {
                return ResourceManager.GetString("WaterfallLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows Waterfall Chart.
        /// </summary>
        public static string WaterfallSummary {
            get {
                return ResourceManager.GetString("WaterfallSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterfall Chart.
        /// </summary>
        public static string WaterfallTitle {
            get {
                return ResourceManager.GetString("WaterfallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Totals.
        /// </summary>
        public static string WaterfallTotal {
            get {
                return ResourceManager.GetString("WaterfallTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlexChart&apos;s itemsSource and binding/bindingX properties apply to all series in the chart by default.
        ///
        ///Specific series may override those properties and use different data sources and bindings. This allows you to use multiple data sources on the same chart, and reduces the need to pre-process data for charting..
        /// </summary>
        public static string XYScatterDescription {
            get {
                return ResourceManager.GetString("XYScatterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY Scatter Plot.
        /// </summary>
        public static string XYScatterSummary {
            get {
                return ResourceManager.GetString("XYScatterSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY Scatter Plot.
        /// </summary>
        public static string XYScatterTitle {
            get {
                return ResourceManager.GetString("XYScatterTitle", resourceCulture);
            }
        }
    }
}
