//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GaugeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GaugeRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorExplorer.Localization.GaugeRes", typeof(GaugeRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet Graph.
        /// </summary>
        public static string BulletGraph {
            get {
                return ResourceManager.GetString("BulletGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Gauge.
        /// </summary>
        public static string LinearGauge {
            get {
                return ResourceManager.GetString("LinearGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows basic LinearGauge, BulletGraph and RadialGauge features..
        /// </summary>
        public static string OverviewDescription {
            get {
                return ResourceManager.GetString("OverviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows basic LinearGauge, BulletGraph and RadialGauge features..
        /// </summary>
        public static string OverviewSummary {
            get {
                return ResourceManager.GetString("OverviewSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string OverviewTitle {
            get {
                return ResourceManager.GetString("OverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial Gauge.
        /// </summary>
        public static string RadialGauge {
            get {
                return ResourceManager.GetString("RadialGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversed.
        /// </summary>
        public static string Reversed {
            get {
                return ResourceManager.GetString("Reversed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string ValueText {
            get {
                return ResourceManager.GetString("ValueText", resourceCulture);
            }
        }
    }
}
