<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Remove=".sa3licx" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include=".sa3licx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="C1.Blazor.Core">
      <Version>10.0.20261.126</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.Grid">
      <Version>10.0.20261.126</Version>
    </PackageReference>
    <PackageReference Include="C1.DataCollection.Serialization">
      <Version>10.0.20261.8</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Client\FlexGridDataVirtualization.Client.csproj" />
    <ProjectReference Include="..\Shared\FlexGridDataVirtualization.Shared.csproj" />
  </ItemGroup>
</Project>