<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Remove=".sa3licx" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include=".sa3licx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="C1.Blazor.Chart">
      <Version>10.0.20261.50</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.Core">
      <Version>10.0.20261.50</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.DataPager">
      <Version>10.0.20261.50</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.Grid">
      <Version>10.0.20261.50</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.Input">
      <Version>10.0.20261.50</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.ListView">
      <Version>10.0.20261.50</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\FlightStatistics.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Localization\FlightStatisticsRes.resx">
      <Generator>
      </Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>