//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccordionExplorer.Server.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccordionRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccordionRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccordionExplorer.Server.Localization.AccordionRes", typeof(AccordionRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Accordion control allows you to organize content into collapsible panels. This sample demonstrates the usage and main properties of the Accordion control..
        /// </summary>
        public static string AccordionDescription {
            get {
                return ResourceManager.GetString("AccordionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays an accordion contains some collapsible panels..
        /// </summary>
        public static string AccordionSummary {
            get {
                return ResourceManager.GetString("AccordionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string AccordionTitle {
            get {
                return ResourceManager.GetString("AccordionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Direction.
        /// </summary>
        public static string ExpandDirection {
            get {
                return ResourceManager.GetString("ExpandDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expander control allows you add content into a panel that collapsible..
        /// </summary>
        public static string ExpanderDescription {
            get {
                return ResourceManager.GetString("ExpanderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expander that expand to the Left.
        /// </summary>
        public static string ExpanderExpandLeft {
            get {
                return ResourceManager.GetString("ExpanderExpandLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expander that expand to the Right.
        /// </summary>
        public static string ExpanderExpandRight {
            get {
                return ResourceManager.GetString("ExpanderExpandRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expander that expand to the Top.
        /// </summary>
        public static string ExpanderExpandTop {
            get {
                return ResourceManager.GetString("ExpanderExpandTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display how the Expander works..
        /// </summary>
        public static string ExpanderSummary {
            get {
                return ResourceManager.GetString("ExpanderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expander.
        /// </summary>
        public static string ExpanderTitle {
            get {
                return ResourceManager.GetString("ExpanderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Icon Alignment.
        /// </summary>
        public static string ExpandIconAlignment {
            get {
                return ResourceManager.GetString("ExpandIconAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Mode.
        /// </summary>
        public static string ExpandMode {
            get {
                return ResourceManager.GetString("ExpandMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill remaining space.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header1.
        /// </summary>
        public static string Header1 {
            get {
                return ResourceManager.GetString("Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header2.
        /// </summary>
        public static string Header2 {
            get {
                return ResourceManager.GetString("Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header3.
        /// </summary>
        public static string Header3 {
            get {
                return ResourceManager.GetString("Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header4.
        /// </summary>
        public static string Header4 {
            get {
                return ResourceManager.GetString("Header4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve content.
        /// </summary>
        public static string PreserveContent {
            get {
                return ResourceManager.GetString("PreserveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to newsletter.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
