//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FlexGridRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlexGridRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorExplorer.Localization.FlexGridRes", typeof(FlexGridRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert!.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select row to edit..
        /// </summary>
        public static string AlertText {
            get {
                return ResourceManager.GetString("AlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Resizing.
        /// </summary>
        public static string AllowResizingLabel {
            get {
                return ResourceManager.GetString("AllowResizingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexGrid supports freezing rows and columns so that they remain static as the user scrolls..
        /// </summary>
        public static string CellFreezingDescription {
            get {
                return ResourceManager.GetString("CellFreezingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows frozen columns, rows and cell merging..
        /// </summary>
        public static string CellFreezingSummary {
            get {
                return ResourceManager.GetString("CellFreezingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Freezing &amp; Merging.
        /// </summary>
        public static string CellFreezingTitle {
            get {
                return ResourceManager.GetString("CellFreezingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexGrid supports cell merging. Data across rows or down columns can be automatically merged when working with bound data. Cells can even be merged in both directions if the data values are the same..
        /// </summary>
        public static string CellMergingDescription {
            get {
                return ResourceManager.GetString("CellMergingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a grid with cell merging..
        /// </summary>
        public static string CellMergingSummary {
            get {
                return ResourceManager.GetString("CellMergingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells Merging.
        /// </summary>
        public static string CellMergingTitle {
            get {
                return ResourceManager.GetString("CellMergingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cell(s) selected.
        /// </summary>
        public static string CellsSelectedText {
            get {
                return ResourceManager.GetString("CellsSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable selection of multiple, non-adjacent rows using check-boxes. This feature is built-in using a FlexGrid behavior..
        /// </summary>
        public static string CheckListDescription {
            get {
                return ResourceManager.GetString("CheckListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show how to select flexgrid rows through checkboxes..
        /// </summary>
        public static string CheckListSummary {
            get {
                return ResourceManager.GetString("CheckListSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-List.
        /// </summary>
        public static string CheckListTitle {
            get {
                return ResourceManager.GetString("CheckListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color coded updates.
        /// </summary>
        public static string ColorUpdates {
            get {
                return ResourceManager.GetString("ColorUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, columns are automatically generated when you bind FlexGrid to a data source. For complete control over which columns are displayed, and in what order, you may define the columns yourself and disable the automatic generation. This demo shows how to define columns in markup, as well as format number and date values..
        /// </summary>
        public static string ColumnDefinitionDescription {
            get {
                return ResourceManager.GetString("ColumnDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to specify and format columns..
        /// </summary>
        public static string ColumnDefinitionSummary {
            get {
                return ResourceManager.GetString("ColumnDefinitionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Definitions.
        /// </summary>
        public static string ColumnDefinitionTitle {
            get {
                return ResourceManager.GetString("ColumnDefinitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a custom column manager to modify column layout..
        /// </summary>
        public static string ColumnLayoutDescription {
            get {
                return ResourceManager.GetString("ColumnLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demos how to customize the grid&apos;s column layout by hiding unnecessary columns and reordering them..
        /// </summary>
        public static string ColumnLayoutSummary {
            get {
                return ResourceManager.GetString("ColumnLayoutSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Layout.
        /// </summary>
        public static string ColumnLayoutTitle {
            get {
                return ResourceManager.GetString("ColumnLayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GridCellFactory class is used to create custom cells in FlexGrid. In addition to supporting custom elements within cells, the cell factory can be used to provide complete control over the display of each cell. In this demo, a cell factory is used to customize the cell background and text colors based upon the cell values..
        /// </summary>
        public static string ConditionalFormattingDescription {
            get {
                return ResourceManager.GetString("ConditionalFormattingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses a CellFactory to apply conditional formatting..
        /// </summary>
        public static string ConditionalFormattingSummary {
            get {
                return ResourceManager.GetString("ConditionalFormattingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Formatting.
        /// </summary>
        public static string ConditionalFormattingTitle {
            get {
                return ResourceManager.GetString("ConditionalFormattingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexGrid contains many properties that allow you to easily style all visual aspects of the grid. This includes column headers, row headers, selection adorners, gridlines, selected cells, and cell padding..
        /// </summary>
        public static string CustomAppearanceDescription {
            get {
                return ResourceManager.GetString("CustomAppearanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a grid with a custom style..
        /// </summary>
        public static string CustomAppearanceSummary {
            get {
                return ResourceManager.GetString("CustomAppearanceSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Appearance.
        /// </summary>
        public static string CustomAppearanceTitle {
            get {
                return ResourceManager.GetString("CustomAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizes a cell by displaying a numeric value in a gauge..
        /// </summary>
        public static string CustomCellsDescription {
            get {
                return ResourceManager.GetString("CustomCellsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Cells.
        /// </summary>
        public static string CustomCellsTitle {
            get {
                return ResourceManager.GetString("CustomCellsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows several custom columns including images, numeric input, date &amp; time and cell text with wrapping..
        /// </summary>
        public static string CustomColumnDescription {
            get {
                return ResourceManager.GetString("CustomColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to customize different kinds of columns.
        /// </summary>
        public static string CustomColumnSummary {
            get {
                return ResourceManager.GetString("CustomColumnSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Column.
        /// </summary>
        public static string CustomColumnTitle {
            get {
                return ResourceManager.GetString("CustomColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data displayed within FlexGrid can be quickly sorted by clicking or tapping column headers. This demo shows how to customize the sort icon position and template..
        /// </summary>
        public static string CustomSortIconDescription {
            get {
                return ResourceManager.GetString("CustomSortIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show how to customize the sorting icon in header columns..
        /// </summary>
        public static string CustomSortIconSummary {
            get {
                return ResourceManager.GetString("CustomSortIconSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Sort Icon.
        /// </summary>
        public static string CustomSortIconTitle {
            get {
                return ResourceManager.GetString("CustomSortIconTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailsVisibiltyMode.
        /// </summary>
        public static string DetailsVisibiltyMode {
            get {
                return ResourceManager.GetString("DetailsVisibiltyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditColumnLayout {
            get {
                return ResourceManager.GetString("EditColumnLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This demo shows how to prompt the user with a confirmation dialog before committing changes to a cell..
        /// </summary>
        public static string EditConfirmationDescription {
            get {
                return ResourceManager.GetString("EditConfirmationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to commit the edit?.
        /// </summary>
        public static string EditConfirmationQuestion {
            get {
                return ResourceManager.GetString("EditConfirmationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Edit.
        /// </summary>
        public static string EditConfirmationQuestionTitle {
            get {
                return ResourceManager.GetString("EditConfirmationQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to prompt the user with a confirmation dialog before committing changes to a cell..
        /// </summary>
        public static string EditConfirmationSummary {
            get {
                return ResourceManager.GetString("EditConfirmationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Confirmation.
        /// </summary>
        public static string EditConfirmationTitle {
            get {
                return ResourceManager.GetString("EditConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit cells by input form rather than inline..
        /// </summary>
        public static string EditingDescription {
            get {
                return ResourceManager.GetString("EditingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Form.
        /// </summary>
        public static string EditingTitle {
            get {
                return ResourceManager.GetString("EditingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit item.
        /// </summary>
        public static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Row.
        /// </summary>
        public static string EditRow {
            get {
                return ResourceManager.GetString("EditRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected item.
        /// </summary>
        public static string EditSelectedItem {
            get {
                return ResourceManager.GetString("EditSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no videos to show..
        /// </summary>
        public static string EmptyListText {
            get {
                return ResourceManager.GetString("EmptyListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Save method allows exporting the data shown in the grid to CSV, text, and HTML..
        /// </summary>
        public static string ExportDescription {
            get {
                return ResourceManager.GetString("ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to export to CSV, text, and HTML..
        /// </summary>
        public static string ExportSummary {
            get {
                return ResourceManager.GetString("ExportSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by condition.
        /// </summary>
        public static string FilterByCondition {
            get {
                return ResourceManager.GetString("FilterByCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by values.
        /// </summary>
        public static string FilterByValues {
            get {
                return ResourceManager.GetString("FilterByValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to filter.
        /// </summary>
        public static string FilterPlaceholderText {
            get {
                return ResourceManager.GetString("FilterPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters the data by columns through GridFilterRow..
        /// </summary>
        public static string FilterRowDescription {
            get {
                return ResourceManager.GetString("FilterRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters the data by columns through GridFilterRow..
        /// </summary>
        public static string FilterRowSummary {
            get {
                return ResourceManager.GetString("FilterRowSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Row.
        /// </summary>
        public static string FilterRowTitle {
            get {
                return ResourceManager.GetString("FilterRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-text filtering is the simplest way to filter FlexGrid. Simply bind a text box (such as C1TextBox) to the FlexGrid’s filter behavior and get instant filtering that can match exact case, partial text or whole words across all columns of the grid. You can also set the highlight text color..
        /// </summary>
        public static string FullTextFilterDescription {
            get {
                return ResourceManager.GetString("FullTextFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters and highlights the data across all columns..
        /// </summary>
        public static string FullTextFilterSummary {
            get {
                return ResourceManager.GetString("FullTextFilterSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Text Filter.
        /// </summary>
        public static string FullTextFilterTitle {
            get {
                return ResourceManager.GetString("FullTextFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display, edit and aggregate your data all at once with FlexGrid..
        /// </summary>
        public static string GettingStartedDescription {
            get {
                return ResourceManager.GetString("GettingStartedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string GettingStartedTitle {
            get {
                return ResourceManager.GetString("GettingStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample demos how to customize a GridColumn of FlexGrid. The &quot;Country&quot; column has edited using a dropdown instead of textbox editor..
        /// </summary>
        public static string GridColumnCustomizationDescription {
            get {
                return ResourceManager.GetString("GridColumnCustomizationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridColumn customization.
        /// </summary>
        public static string GridColumnCustomizationTitle {
            get {
                return ResourceManager.GetString("GridColumnCustomizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by department.
        /// </summary>
        public static string GroupByDepartmentText {
            get {
                return ResourceManager.GetString("GroupByDepartmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexGrid can display data that is grouped and aggregated through C1DataCollection. You can customize the text that is displayed in group header rows using the grid&apos;s GroupHeaderFormat property..
        /// </summary>
        public static string GroupingDescription {
            get {
                return ResourceManager.GetString("GroupingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups and aggregates a collection of data..
        /// </summary>
        public static string GroupingSummary {
            get {
                return ResourceManager.GetString("GroupingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string GroupingTitle {
            get {
                return ResourceManager.GetString("GroupingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a tree-like data-source bound to FlexGrid using ChildItemsPath property..
        /// </summary>
        public static string HierarchicalRowsDescription {
            get {
                return ResourceManager.GetString("HierarchicalRowsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HierarchicalRowsSummary {
            get {
                return ResourceManager.GetString("HierarchicalRowsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hierarchical Rows.
        /// </summary>
        public static string HierarchicalRowsTitle {
            get {
                return ResourceManager.GetString("HierarchicalRowsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to animates changes in the grid..
        /// </summary>
        public static string LiveUpdatesDescription {
            get {
                return ResourceManager.GetString("LiveUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live updates.
        /// </summary>
        public static string LiveUpdatesTitle {
            get {
                return ResourceManager.GetString("LiveUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string MatchCaseLabel {
            get {
                return ResourceManager.GetString("MatchCaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Whole Word.
        /// </summary>
        public static string MatchWholeWordLabel {
            get {
                return ResourceManager.GetString("MatchWholeWordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users can add rows to the data grid using the add new row feature. The new row placeholder can be at the top or bottom of the grid..
        /// </summary>
        public static string NewRowDescription {
            get {
                return ResourceManager.GetString("NewRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add a new row.
        /// </summary>
        public static string NewRowPlaceholder {
            get {
                return ResourceManager.GetString("NewRowPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows adding new rows..
        /// </summary>
        public static string NewRowSummary {
            get {
                return ResourceManager.GetString("NewRowSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Row.
        /// </summary>
        public static string NewRowTitle {
            get {
                return ResourceManager.GetString("NewRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With on-demand loading, FlexGrid loads items as the user scrolls. This is different from virtual mode because the grid never knows the total number of rows, so the scroll bar size and position changes as more data is loaded into the grid. This virtualization technique is supported by the help of C1DataCollection..
        /// </summary>
        public static string OnDemandDescription {
            get {
                return ResourceManager.GetString("OnDemandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load items on demand as the user scrolls down the grid..
        /// </summary>
        public static string OnDemandSummary {
            get {
                return ResourceManager.GetString("OnDemandSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Demand.
        /// </summary>
        public static string OnDemandTitle {
            get {
                return ResourceManager.GetString("OnDemandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The native FlexGrid for Blazor control allows you to display, select, edit, sort, group and filter tabular and hierarchical data. It provides exceptional flexibility and customization for cell editing and appearance. Plus, it supports smart, on-demand loading for large data sets, responsive sizing, and many Microsoft Excel-like spreadsheet features such as cell freezing and merging..
        /// </summary>
        public static string OverviewDescription {
            get {
                return ResourceManager.GetString("OverviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string OverviewTitle {
            get {
                return ResourceManager.GetString("OverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable paging using the C1DataPager to navigate through different pages of data bound to FlexGrid. Like the virtual mode and on-demand loading, paging is supported by the help of C1DataCollection..
        /// </summary>
        public static string PagingDescription {
            get {
                return ResourceManager.GetString("PagingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to use C1DataPager to navigate through different  pages of data bound to FlexGrid.
        /// </summary>
        public static string PagingSummary {
            get {
                return ResourceManager.GetString("PagingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging.
        /// </summary>
        public static string PagingTitle {
            get {
                return ResourceManager.GetString("PagingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Column.
        /// </summary>
        public static string PinColumn {
            get {
                return ResourceManager.GetString("PinColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to implement pin/unpin columns so they become frozen at the left edge of the grid while scrolling horizontally..
        /// </summary>
        public static string PinColumnDescription {
            get {
                return ResourceManager.GetString("PinColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Column.
        /// </summary>
        public static string PinColumnTitle {
            get {
                return ResourceManager.GetString("PinColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexGrid can be responsively sized, meaning the column widths can adjust automatically to nicely fill the entire available space no matter what browser or device is being used. This is known as star-sizing, and you can configure each column to be proportionally sized such as 2*, 3*, and so on..
        /// </summary>
        public static string ResponsiveSizingDescription {
            get {
                return ResourceManager.GetString("ResponsiveSizingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the device to see star-sizing in action..
        /// </summary>
        public static string ResponsiveSizingInstructions {
            get {
                return ResourceManager.GetString("ResponsiveSizingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a responsive column layout that uses star sizing..
        /// </summary>
        public static string ResponsiveSizingSummary {
            get {
                return ResourceManager.GetString("ResponsiveSizingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsive Sizing.
        /// </summary>
        public static string ResponsiveSizingTitle {
            get {
                return ResourceManager.GetString("ResponsiveSizingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a row details section enables you to make a hierarchical grid by grouping some data in a template that is collapsed beneath each row. For example, you can add row details to a FlexGrid that presents only a summary of the data for each row but presents more data when the user selects a row..
        /// </summary>
        public static string RowDetailsDescription {
            get {
                return ResourceManager.GetString("RowDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand and collapse row details..
        /// </summary>
        public static string RowDetailsSummary {
            get {
                return ResourceManager.GetString("RowDetailsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Details.
        /// </summary>
        public static string RowDetailsTitle {
            get {
                return ResourceManager.GetString("RowDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to search videos on YouTube.
        /// </summary>
        public static string SearchPlaceholderText {
            get {
                return ResourceManager.GetString("SearchPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage how cells are selected by setting the selection mode. FlexGrid supports single row, column and cell selection modes, (plus ranges when the user holds the SHIFT key, and multiple ranges by pressing CTRL key) The selected cell data can then be easily retrieved through the control’s Selection and SeletedRanges properties..
        /// </summary>
        public static string SelectionModesDescription {
            get {
                return ResourceManager.GetString("SelectionModesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Modes.
        /// </summary>
        public static string SelectionModesLabel {
            get {
                return ResourceManager.GetString("SelectionModesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the various cell selection modes..
        /// </summary>
        public static string SelectionModesSummary {
            get {
                return ResourceManager.GetString("SelectionModesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Modes.
        /// </summary>
        public static string SelectionModesTitle {
            get {
                return ResourceManager.GetString("SelectionModesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row first or double-tap the row directly..
        /// </summary>
        public static string SelectRowMessage {
            get {
                return ResourceManager.GetString("SelectRowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowMarquee.
        /// </summary>
        public static string ShowMarquee {
            get {
                return ResourceManager.GetString("ShowMarquee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show sort icons.
        /// </summary>
        public static string ShowSort {
            get {
                return ResourceManager.GetString("ShowSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort icon position.
        /// </summary>
        public static string SortIconPosition {
            get {
                return ResourceManager.GetString("SortIconPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort icon template.
        /// </summary>
        public static string SortIconTemplate {
            get {
                return ResourceManager.GetString("SortIconTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more symbols.
        /// </summary>
        public static string StockSymbolSelectText {
            get {
                return ResourceManager.GetString("StockSymbolSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryRows allow displaying aggregating values that are calculated from the AggregateFunctions in the corresponding columns..
        /// </summary>
        public static string SummaryRowDescription {
            get {
                return ResourceManager.GetString("SummaryRowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a row that summarizes the values in the columns.
        /// </summary>
        public static string SummaryRowSummary {
            get {
                return ResourceManager.GetString("SummaryRowSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Row.
        /// </summary>
        public static string SummaryRowTitle {
            get {
                return ResourceManager.GetString("SummaryRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show how to transpose columns and rows so the data items are shown as columns..
        /// </summary>
        public static string TransposedGridDescription {
            get {
                return ResourceManager.GetString("TransposedGridDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transposed Grid.
        /// </summary>
        public static string TransposedGridTitle {
            get {
                return ResourceManager.GetString("TransposedGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In addition to displaying bound data, FlexGrid can be used completely unbound. Add any number of rows and columns and populate the cells programmatically or let the end-user fill them in like a spreadsheet..
        /// </summary>
        public static string UnboundDescription {
            get {
                return ResourceManager.GetString("UnboundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add empty rows and columns to create an unbound grid..
        /// </summary>
        public static string UnboundSummary {
            get {
                return ResourceManager.GetString("UnboundSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbound.
        /// </summary>
        public static string UnboundTitle {
            get {
                return ResourceManager.GetString("UnboundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin Column.
        /// </summary>
        public static string UnpinColumn {
            get {
                return ResourceManager.GetString("UnpinColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show how to display and style validation.
        /// </summary>
        public static string ValidationDescription {
            get {
                return ResourceManager.GetString("ValidationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string ValidationTitle {
            get {
                return ResourceManager.GetString("ValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexGrid supports data virtualization for faster performance for very large data sets. With virtual mode, data is fetched in pages as the user scrolls. The grid knows the total number of rows but only loads and displays those that are visible to the user. This virtualization technique is supported by the help of C1DataCollection..
        /// </summary>
        public static string VirtualModeDescription {
            get {
                return ResourceManager.GetString("VirtualModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to bind FlexGrid to a data source whose items are fetch as the user scroll down..
        /// </summary>
        public static string VirtualModeSummary {
            get {
                return ResourceManager.GetString("VirtualModeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Mode.
        /// </summary>
        public static string VirtualModeTitle {
            get {
                return ResourceManager.GetString("VirtualModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        public static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        public static string Weekend {
            get {
                return ResourceManager.GetString("Weekend", resourceCulture);
            }
        }
    }
}
