//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExcelRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExcelRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorExplorer.Localization.ExcelRes", typeof(ExcelRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page demonstrates fetching data from the client..
        /// </summary>
        public static string ClientFetch {
            get {
                return ResourceManager.GetString("ClientFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp. (C).
        /// </summary>
        public static string CTemp {
            get {
                return ResourceManager.GetString("CTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Excel file name and format.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page demonstrates fetching Excel file data from the server..
        /// </summary>
        public static string ExcelFetch {
            get {
                return ResourceManager.GetString("ExcelFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string ExcelTitle {
            get {
                return ResourceManager.GetString("ExcelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Save method allows exporting the data shown in the FlexGrid to Excel formats..
        /// </summary>
        public static string ExportDescription {
            get {
                return ResourceManager.GetString("ExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to export FlexGrid data to Excel formats..
        /// </summary>
        public static string ExportSummary {
            get {
                return ResourceManager.GetString("ExportSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportTitle {
            get {
                return ResourceManager.GetString("ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows how to fetch data and save them into Excel file on the client..
        /// </summary>
        public static string FetchDataDescription {
            get {
                return ResourceManager.GetString("FetchDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to export sample data to Excel formats..
        /// </summary>
        public static string FetchDataSummary {
            get {
                return ResourceManager.GetString("FetchDataSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Data.
        /// </summary>
        public static string FetchDataTitle {
            get {
                return ResourceManager.GetString("FetchDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows how you can read data from the downloaded Excel file on the client side..
        /// </summary>
        public static string FetchExcelDescription {
            get {
                return ResourceManager.GetString("FetchExcelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to read Excel file on the client..
        /// </summary>
        public static string FetchExcelSummary {
            get {
                return ResourceManager.GetString("FetchExcelSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Excel file.
        /// </summary>
        public static string FetchExcelTitle {
            get {
                return ResourceManager.GetString("FetchExcelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp. (F).
        /// </summary>
        public static string FTemp {
            get {
                return ResourceManager.GetString("FTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The C1.Excel library allows to save data into XLSX (Open XML format), XLS (Binary BIFF8 format) and CSV (Comma Separated Values format)..
        /// </summary>
        public static string IndexDescription {
            get {
                return ResourceManager.GetString("IndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one sheet or all.
        /// </summary>
        public static string IndexSheets {
            get {
                return ResourceManager.GetString("IndexSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows how to create and save Excel file using C1.Excel library..
        /// </summary>
        public static string IndexSummary {
            get {
                return ResourceManager.GetString("IndexSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page demonstrates fetching data from the server..
        /// </summary>
        public static string ServerFetch {
            get {
                return ResourceManager.GetString("ServerFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        public static string WeatherForecast {
            get {
                return ResourceManager.GetString("WeatherForecast", resourceCulture);
            }
        }
    }
}
