//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TooltipRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TooltipRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorExplorer.Localization.TooltipRes", typeof(TooltipRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is sample of &lt;b&gt;&lt;span id=&quot;testTooltip&quot;&gt;tooltip&lt;/span&gt;&lt;/b&gt;. Hover on it and its tooltip will be displayed..
        /// </summary>
        public static string Index_Text0 {
            get {
                return ResourceManager.GetString("Index_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can add a tooltip for a span element, or a button like this. &lt;br /&gt;
        ///  &lt;button class=&quot;btn btn-default&quot; id=&quot;btnOpenPopup&quot;&gt;Hover me!&lt;/button&gt;.
        /// </summary>
        public static string Index_Text1 {
            get {
                return ResourceManager.GetString("Index_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is at the Bottom and aligned to the Left of the referenced element..
        /// </summary>
        public static string Index_Text10 {
            get {
                return ResourceManager.GetString("Index_Text10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is at the Bottom of the referenced element..
        /// </summary>
        public static string Index_Text11 {
            get {
                return ResourceManager.GetString("Index_Text11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is at the Bottom and aligned to the Right of the referenced element..
        /// </summary>
        public static string Index_Text12 {
            get {
                return ResourceManager.GetString("Index_Text12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is on the Left and aligned to the Top of the referenced element..
        /// </summary>
        public static string Index_Text13 {
            get {
                return ResourceManager.GetString("Index_Text13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is on the Left of the referenced element..
        /// </summary>
        public static string Index_Text14 {
            get {
                return ResourceManager.GetString("Index_Text14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is on the Left and aligned to the Bottom of the referenced element..
        /// </summary>
        public static string Index_Text15 {
            get {
                return ResourceManager.GetString("Index_Text15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is on the Right and aligned to the Top of the referenced element..
        /// </summary>
        public static string Index_Text16 {
            get {
                return ResourceManager.GetString("Index_Text16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is on the Right of the referenced element..
        /// </summary>
        public static string Index_Text17 {
            get {
                return ResourceManager.GetString("Index_Text17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is on the Right and aligned to the Bottom of the referenced element..
        /// </summary>
        public static string Index_Text18 {
            get {
                return ResourceManager.GetString("Index_Text18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can display a tooltip with the custom content. Hover this &lt;span id=&quot;ttcustom&quot; style=&quot;font:bolder;color:brown&quot;&gt;span&lt;/span&gt; for sample..
        /// </summary>
        public static string Index_Text2 {
            get {
                return ResourceManager.GetString("Index_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip can be displayed at different positions around the target element like it is shown below..
        /// </summary>
        public static string Index_Text3 {
            get {
                return ResourceManager.GetString("Index_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is text content.
        /// </summary>
        public static string Index_Text4 {
            get {
                return ResourceManager.GetString("Index_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is tooltip of button.
        /// </summary>
        public static string Index_Text5 {
            get {
                return ResourceManager.GetString("Index_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;ttPanel&quot;&gt;
        ///      &lt;div class=&quot;ttTitle&quot;&gt;Title of tooltip box&lt;/div&gt;
        ///      &lt;div class=&quot;ttContent&quot;&gt;This is a &lt;b&gt;box&lt;/b&gt; tooltip &lt;br /&gt;content&lt;/div&gt;
        ///    &lt;/div&gt;.
        /// </summary>
        public static string Index_Text6 {
            get {
                return ResourceManager.GetString("Index_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is at the Top and aligned to the Left of the referenced element..
        /// </summary>
        public static string Index_Text7 {
            get {
                return ResourceManager.GetString("Index_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is at the Top of the referenced element..
        /// </summary>
        public static string Index_Text8 {
            get {
                return ResourceManager.GetString("Index_Text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tooltip is at the Top and aligned to the Right of the referenced element..
        /// </summary>
        public static string Index_Text9 {
            get {
                return ResourceManager.GetString("Index_Text9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltips for validating input fields..
        /// </summary>
        public static string InputFormDesc {
            get {
                return ResourceManager.GetString("InputFormDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip for validation.
        /// </summary>
        public static string InputFormSummary {
            get {
                return ResourceManager.GetString("InputFormSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate the input fields..
        /// </summary>
        public static string InputFormTitle {
            get {
                return ResourceManager.GetString("InputFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip is a floating popup that appear when the user moves the mouse over target elements.&lt;br /&gt; Use the Target property to associate a tooltip with elements on the page &lt;br /&gt;By default, tooltips are positioned above the target element. User can change that default by specifying the position where the tooltip should appear. &lt;br /&gt;&lt;br /&gt;This sample adds tooltips to some span elements and to a button. The table shows all value of PopupPosition..
        /// </summary>
        public static string OverviewDescription {
            get {
                return ResourceManager.GetString("OverviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip allows user to add a floating popup that appears when the user moves the mouse over target elements..
        /// </summary>
        public static string OverviewSummary {
            get {
                return ResourceManager.GetString("OverviewSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string OverviewTitle {
            get {
                return ResourceManager.GetString("OverviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Validation_Age {
            get {
                return ResourceManager.GetString("Validation_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Validation_Comment {
            get {
                return ResourceManager.GetString("Validation_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Validation_Name {
            get {
                return ResourceManager.GetString("Validation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Validation_Password {
            get {
                return ResourceManager.GetString("Validation_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Validation_Submit {
            get {
                return ResourceManager.GetString("Validation_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need input the Name!.
        /// </summary>
        public static string Validation_Text0 {
            get {
                return ResourceManager.GetString("Validation_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age should not be empty..
        /// </summary>
        public static string Validation_Text1 {
            get {
                return ResourceManager.GetString("Validation_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your age is:.
        /// </summary>
        public static string Validation_Text10 {
            get {
                return ResourceManager.GetString("Validation_Text10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is:.
        /// </summary>
        public static string Validation_Text11 {
            get {
                return ResourceManager.GetString("Validation_Text11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user name is:.
        /// </summary>
        public static string Validation_Text12 {
            get {
                return ResourceManager.GetString("Validation_Text12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is:.
        /// </summary>
        public static string Validation_Text13 {
            get {
                return ResourceManager.GetString("Validation_Text13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string Validation_Text14 {
            get {
                return ResourceManager.GetString("Validation_Text14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age should be number and greater than 18..
        /// </summary>
        public static string Validation_Text2 {
            get {
                return ResourceManager.GetString("Validation_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is required..
        /// </summary>
        public static string Validation_Text3 {
            get {
                return ResourceManager.GetString("Validation_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need input the user name..
        /// </summary>
        public static string Validation_Text4 {
            get {
                return ResourceManager.GetString("Validation_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name should has length &gt;= 5..
        /// </summary>
        public static string Validation_Text5 {
            get {
                return ResourceManager.GetString("Validation_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need input the pass word..
        /// </summary>
        public static string Validation_Text6 {
            get {
                return ResourceManager.GetString("Validation_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should has length &gt;= 8..
        /// </summary>
        public static string Validation_Text7 {
            get {
                return ResourceManager.GetString("Validation_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your inputs.
        /// </summary>
        public static string Validation_Text8 {
            get {
                return ResourceManager.GetString("Validation_Text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name is:.
        /// </summary>
        public static string Validation_Text9 {
            get {
                return ResourceManager.GetString("Validation_Text9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Validation_User {
            get {
                return ResourceManager.GetString("Validation_User", resourceCulture);
            }
        }
    }
}
