<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Remove=".sa3licx" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include=".sa3licx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="C1.Blazor.Accordion">
      <Version>10.0.20261.126</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.Core">
      <Version>10.0.20261.126</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.DataFilter">
      <Version>10.0.20261.126</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.DateTimeEditors">
      <Version>10.0.20261.126</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.Grid">
      <Version>10.0.20261.126</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.GridControl">
      <Version>10.0.20261.126</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.Input">
      <Version>10.0.20261.126</Version>
    </PackageReference>
    <PackageReference Include="C1.Blazor.ListView">
      <Version>10.0.20261.126</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Localization\AccordionRes.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AccordionRes.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Localization\AccordionRes.ja.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\AccordionRes.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AccordionRes.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Folder Include="Localization\" />
  </ItemGroup>
</Project>